---
- name: delete routes
  command: sudo route del -net {{ item.ip | regex_search('\d{1,3}.\d{1,3}.\d{1,3}.')}}0 gw 0.0.0.0 netmask 255.255.255.0 dev {{ item.bridge }}
  when: item.skip is not defined